### ISSUE TITLE
VQVAE train/test splits

### ISSUE THREAD

**Issue by peter-yh-wu** [RanyaJumah/EDGY#1]
Are there scripts to generate the VQVAE train/test splits .json files? Would like to try preprocessing & then training the model.

**Comment by RanyaJumah** [comment]
Hello peter-yh-wu, and thank you for your interest!
For the JSON files, you need to create it for the dataset that you want to use following this structure: [input_path/filename, starting_time, duration, output_path/filename] , the filename should be without the .wav extension, then these Json files will be used by "Preprocessing.py", and the preprocessing output will be used by the training script.

**Comment by dimitriStoidis** [comment]
Would it be possible to provide an example of .json files for example for LibriSpeech dataset?
